### ISSUE TITLE
azure subscription expired for dnsrecord zone

### ISSUE THREAD

**Issue by curx** [23technologies/okeanos#6]
Reconcile Failed:

```
Error reconciling DNSRecord: could not create or update DNS recordset in zone okeanos/okeanos.dev
...
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token ... https://management.azure.com/subscriptions/... : StatusCode=401 -- Original Error: adal: Refresh request failed.
...

The provided client secret keys for app 'd...0' are expired.
```

**Comment by berendt** [comment]
Thank you for pointing this out. It probably makes sense if you use okeanos.tech instead of okeanos.dev in the future. okeanos.dev has become more of a staging environment and playground for us. To login to okeanos.tech you need a REGIO.id on REGIO.login. I can prepare and set this up so far. okeanos.tech ist der Managed Kubernetes Layer auf REGIO.

**Comment by curx** [comment]
Thanks @berendt - and login to  okeanos.tech makes more sense to me. I would be grateful for access via OIDC for the okeanos.tech
